version: '3'
services:
  oauther:
    restart: unless-stopped
    build: .
    tty: true
    ports:
      - "80:5000"
    volumes:
      - ./database.json:/database.json
      - ./config.yml:/config.yml
      
